apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-k8s-demo
  namespace: gitlab
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`k8s-demo.wzxmt.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: gitlab-k8s-demo
      port: 8000